name: Publish patched packages to crates.io
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry-run"
        type: boolean
        default: true

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          fetch-depth: 0

      - name: Publish crate.io packages
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run && '--dry-run' || '' }}
        run: |
          cargo publish -p tfhe-ark-ff --token ${{ env.CRATES_TOKEN }} ${{ env.DRY_RUN }}
          cargo publish -p tfhe-ark-poly --token ${{ env.CRATES_TOKEN }} ${{ env.DRY_RUN }}
          cargo publish -p tfhe-ark-ec --token ${{ env.CRATES_TOKEN }} ${{ env.DRY_RUN }}
          cargo publish -p tfhe-ark-bls12-381 --token ${{ env.CRATES_TOKEN }} ${{ env.DRY_RUN }}
